### ISSUE TITLE
Définition d'un pitch 

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/seminaire#1]
# Définition d'un pitch

**Comment by DanielBMY** [comment]
🎵 Pitch don't kill my viiibe, pitch don't kill my vibe ! 🎵 
Okay je sors ! :D

**Comment by douglasduteil** [comment]
<img src=https://media.giphy.com/media/3o7buhFkzTO5BMGPEQ/giphy.gif width=693>

**Comment by DanielBMY** [comment]
damn ! jviens dvoir : they did it @Startupfood !
https://www.youtube.com/watch?v=loqZaxPl56E

**Comment by douglasduteil** [comment]
The Family ! Et il y a Adrien dans le publique \ping @revolunet :laughing:
