### ISSUE TITLE
Libérer les équipes de la dictate de nommage de chaine sur Slack exercé par @douglasduteil the :devil_parrot:

### ISSUE THREAD

**Issue by douglasduteil** [SocialGouv/seminaire#8]
\from @jrduscher 

> on peut virer les caractères grecs devant les channels, c'est contraignanat quand on veut  le citer.
globalement Dougals, ce serait bien de laisser l'équipe projet  décider de ses noms de channel?

**Comment by jrduscher** [comment]
les caractères grecs empechent de citer un channel.


Je suggère 3 temps:
proposition de l'initiative: @douglasduteil 
Discussion en équipe projet
Décision de l'équipe projet.
Mie en oeuvre par @douglasduteil 

je pense qu'il y a des sujets plus importants.
